const SETS=[
  {key:'FIRST',title:'First Stage',sub:'Nov 1999',cards:[
    {id:'C01',nm:'Luffy',r:'h'},
    {id:'C02',nm:'Luffy',r:'h'},
    {id:'C03',nm:'Luffy'},
    {id:'C04',nm:'Luffy'},
    {id:'C05',nm:'Luffy\'s Hat'},
    {id:'C06',nm:'Zoro',r:'h'},
    {id:'C07',nm:'Zoro',r:'h'},
    {id:'C08',nm:'Zoro'},
    {id:'C09',nm:'Nami'},
    {id:'C10',nm:'Nami'},
    {id:'C11',nm:'Nami'},
    {id:'C12',nm:'Usopp'},
    {id:'C13',nm:'Usopp'},
    {id:'C14',nm:'Shanks'},
    {id:'C15',nm:'Beckmann'},
    {id:'C16',nm:'Kuina'},
    {id:'C17',nm:'Koby'},
    {id:'C18',nm:'Rika'},
    {id:'C19',nm:'Boodle'},
    {id:'C20',nm:'Chou-chou'},
    {id:'C21',nm:'Alvida'},
    {id:'C22',nm:'Morgan'},
    {id:'C23',nm:'Helmeppo'},
    {id:'C24',nm:'Buggy'},
    {id:'C25',nm:'Buggy'},
    {id:'C26',nm:'Buggy Cannon'},
    {id:'C27',nm:'Mohji'},
    {id:'C28',nm:'Richie'},
    {id:'C29',nm:'Cabaji'},
    {id:'C30',nm:'Lord of the Coast'},
    {id:'C31',nm:'Alvida Crew'},
    {id:'C32',nm:'Morgan Troops'},
    {id:'C33',nm:'Buggy Crew'},
    {id:'C34',nm:'Red Hair Pirates'},
    {id:'S01',nm:'Luffy Pirates',r:'h'},
    {id:'S02',nm:'Luffy',r:'h'},
    {id:'S03',nm:'Gomu Gomu no Mi',r:'h'},
    {id:'S04',nm:'Zoro',r:'h'},
    {id:'S05',nm:'Nami',r:'h'},
    {id:'S06',nm:'Shanks',r:'h'},
    {id:'S07',nm:'Morgan'},
    {id:'S08',nm:'Buggy'},
  ]},
  {key:'SECOND',title:'2nd Stage',sub:'Jan 2000',cards:[
    {id:'C35',nm:'Luffy',r:'h'},
    {id:'C36',nm:'Luffy',r:'h'},
    {id:'C37',nm:'Luffy',r:'h'},
    {id:'C38',nm:'Zoro',r:'h'},
    {id:'C39',nm:'Zoro',r:'h'},
    {id:'C40',nm:'Zoro'},
    {id:'C41',nm:'Nami'},
    {id:'C42',nm:'Nami'},
    {id:'C43',nm:'Nami'},
    {id:'C44',nm:'Usopp'},
    {id:'C45',nm:'Usopp'},
    {id:'C46',nm:'Usopp\'s Weapon'},
    {id:'C47',nm:'Chou-chou'},
    {id:'C48',nm:'Yasopp'},
    {id:'C49',nm:'Kaya'},
    {id:'C50',nm:'Merry'},
    {id:'C51',nm:'Kurahadol'},
    {id:'C52',nm:'Tamanegi'},
    {id:'C53',nm:'Piiman'},
    {id:'C54',nm:'Ninjin'},
    {id:'C55',nm:'Buggy'},
    {id:'C56',nm:'Buggy'},
    {id:'C57',nm:'Mohji & Richie'},
    {id:'C58',nm:'Cabaji'},
    {id:'C59',nm:'Buggy\'s 3 Underlings'},
    {id:'C60',nm:'Kuro'},
    {id:'C61',nm:'Kuro'},
    {id:'C62',nm:'Jango'},
    {id:'C63',nm:'Jango\'s Weapon'},
    {id:'C64',nm:'Sham'},
    {id:'C65',nm:'Buchi'},
    {id:'C66',nm:'Black Cat Pirates'},
    {id:'S09',nm:'Luffy Pirates',r:'h'},
    {id:'S10',nm:'Luffy',r:'h'},
    {id:'S11',nm:'Zoro',r:'h'},
    {id:'S12',nm:'Usopp',r:'h'},
    {id:'S13',nm:'Sanji',r:'h'},
    {id:'S14',nm:'Buggy',r:'h'},
    {id:'S15',nm:'Kuro'},
    {id:'S16',nm:'Jango'},
    {id:'FP1',nm:'Large Maelstrom'},
    {id:'FP2',nm:'Buggy Pirates'},
  ]},
  {key:'GB1',title:'Grand Box',sub:'Mar 2000',cards:[
    {id:'C67',nm:'Red Hair Pirates'},
    {id:'C68',nm:'Usopp Pirates'},
    {id:'C69',nm:'Luffy',r:'h'},
    {id:'C70',nm:'Luffy',r:'h'},
    {id:'C71',nm:'Luffy\'s Hat'},
    {id:'C72',nm:'Zoro'},
    {id:'C73',nm:'Zoro'},
    {id:'C74',nm:'Zoro'},
    {id:'C75',nm:'Nami'},
    {id:'C76',nm:'Nami'},
    {id:'C77',nm:'Nami\'s Weapon'},
    {id:'C78',nm:'Usopp'},
    {id:'C79',nm:'Usopp'},
    {id:'C80',nm:'Sanji'},
    {id:'C81',nm:'Sanji'},
    {id:'C82',nm:'Shanks',r:'g'},
    {id:'C83',nm:'Shanks'},
    {id:'C84',nm:'Beckmann'},
    {id:'C85',nm:'Lucky Roux'},
    {id:'C86',nm:'Yasopp'},
    {id:'C87',nm:'Makino'},
    {id:'C88',nm:'Koby'},
    {id:'C89',nm:'Rika'},
    {id:'C90',nm:'Kuina'},
    {id:'C91',nm:'Boodle'},
    {id:'C92',nm:'ChuChu'},
    {id:'C93',nm:'Kaya'},
    {id:'C94',nm:'Kurohadol'},
    {id:'C95',nm:'Alvida'},
    {id:'C96',nm:'Morgan'},
    {id:'C97',nm:'Helmeppo'},
    {id:'C98',nm:'Buggy',r:'g'},
    {id:'C99',nm:'Buggy'},
    {id:'C100',nm:'Cabaji'},
    {id:'C101',nm:'Cabaji'},
    {id:'C102',nm:'Mohji & Richie'},
    {id:'C103',nm:'Kuro\'s Weapon'},
    {id:'C104',nm:'Jango'},
    {id:'C105',nm:'Buchi'},
    {id:'C106',nm:'Sham'},
    {id:'C107',nm:'Krieg',r:'g'},
    {id:'C108',nm:'Krieg'},
    {id:'C109',nm:'Buggy Crew'},
    {id:'C110',nm:'Black Cat Pirates'},
    {id:'S17',nm:'Luffy Pirates',r:'h'},
    {id:'S18',nm:'Luffy',r:'h'},
    {id:'S19',nm:'Zoro',r:'h'},
    {id:'S20',nm:'Nami'},
    {id:'S21',nm:'Usopp'},
    {id:'S22',nm:'Shanks'},
    {id:'S23',nm:'Alvida'},
    {id:'S24',nm:'Morgan'},
    {id:'S25',nm:'Buggy'},
    {id:'S26',nm:'Kuro'},
    {id:'FP3',nm:'Usopp\'s Village'},
    {id:'FP4',nm:'Makino\'s Bar'},
    {id:'FP5',nm:'Drinking Pub'},
    {id:'FP6',nm:'Jango\'s Pirates'},
    {id:'FP7',nm:'Going Merry'},
    {id:'FP8',nm:'Baratie is Open for Business'},
  ]},
  {key:'THIRD',title:'3rd Stage',sub:'Apr 2000',cards:[
    {id:'C111',nm:'Luffy'},
    {id:'C112',nm:'Luffy',r:'h'},
    {id:'C113',nm:'Luffy',r:'h'},
    {id:'C114',nm:'Zoro',r:'h'},
    {id:'C115',nm:'Zoro',r:'h'},
    {id:'C116',nm:'Nami'},
    {id:'C117',nm:'Nami'},
    {id:'C118',nm:'Usopp'},
    {id:'C119',nm:'Usopp'},
    {id:'C120',nm:'Sanji'},
    {id:'C121',nm:'Sanji'},
    {id:'C122',nm:'Shanks'},
    {id:'C123',nm:'Shanks'},
    {id:'C124',nm:'Kaya'},
    {id:'C125',nm:'Gaimon'},
    {id:'C126',nm:'Zeff'},
    {id:'C127',nm:'Yosaku'},
    {id:'C128',nm:'Johnny'},
    {id:'C129',nm:'Ganzo'},
    {id:'C130',nm:'Ganzo'},
    {id:'C131',nm:'Tobio'},
    {id:'C132',nm:'Woonan'},
    {id:'C133',nm:'Woonan'},
    {id:'C134',nm:'Kuro'},
    {id:'C135',nm:'Jango'},
    {id:'C136',nm:'Jango'},
    {id:'C137',nm:'Krieg'},
    {id:'C138',nm:'Gin'},
    {id:'C139',nm:'El Drago'},
    {id:'C140',nm:'Golass'},
    {id:'C141',nm:'Luffy Pirates'},
    {id:'C142',nm:'Usopp Pirates'},
    {id:'C143',nm:'Krieg Plunder Force'},
    {id:'C144',nm:'Eldraggo\'s 3 Men'},
    {id:'S27',nm:'Luffy',r:'h'},
    {id:'S28',nm:'Usopp',r:'h'},
    {id:'S29',nm:'Sanji',r:'h'},
    {id:'S30',nm:'Kurohadol',r:'h'},
    {id:'S31',nm:'Krieg',r:'h'},
    {id:'S32',nm:'Eldraggo',r:'h'},
    {id:'FP09',nm:'Krieg Grand Fleet'},
    {id:'FP10',nm:'Baratie Cooking'},
  ]},
  {key:'FOURTH',title:'4th Stage',sub:'Jun 2000',cards:[
    {id:'C145',nm:'Luffy',r:'h'},
    {id:'C146',nm:'Luffy'},
    {id:'C147',nm:'Meat On The Bone'},
    {id:'C148',nm:'Zoro',r:'h'},
    {id:'C149',nm:'Zoro'},
    {id:'C150',nm:'Wado Ichimonji'},
    {id:'C151',nm:'Nami',r:'h'},
    {id:'C152',nm:'Nami',r:'h'},
    {id:'C153',nm:'Usopp'},
    {id:'C154',nm:'Usopp'},
    {id:'C155',nm:'Sanji'},
    {id:'C156',nm:'Sanji'},
    {id:'C157',nm:'Sanji'},
    {id:'C158',nm:'Kuina'},
    {id:'C159',nm:'Gaimon'},
    {id:'C160',nm:'Zeff'},
    {id:'C161',nm:'Zeff'},
    {id:'C162',nm:'Patty'},
    {id:'C163',nm:'Carne'},
    {id:'C164',nm:'Yosaku'},
    {id:'C165',nm:'Johnny'},
    {id:'C166',nm:'Nojiko'},
    {id:'C167',nm:'Bell-mère'},
    {id:'C168',nm:'Genzo'},
    {id:'C169',nm:'Fullbody'},
    {id:'C170',nm:'Mihawk'},
    {id:'C171',nm:'Mihawk\'s Sword'},
    {id:'C172',nm:'Krieg'},
    {id:'C173',nm:'Krieg\'s Weapon'},
    {id:'C174',nm:'Gin'},
    {id:'C175',nm:'Pearl'},
    {id:'C176',nm:'Arlong'},
    {id:'C177',nm:'Fighting Cooks'},
    {id:'S33',nm:'Luffy'},
    {id:'S34',nm:'Zoro',r:'h'},
    {id:'S35',nm:'Nami',r:'h'},
    {id:'S36',nm:'Krieg',r:'h'},
    {id:'S37',nm:'Gin',r:'h'},
    {id:'S38',nm:'Arlong',r:'h'},
    {id:'S39',nm:'Luffy Vs. Arlong',r:'h'},
    {id:'FP11',nm:'Baratie in Battle'},
    {id:'FP12',nm:'Krieg\'s Sunken Ship'},
  ]},
  {key:'GB2',title:'Grand Box 2',sub:'Jul 2000',cards:[
    {id:'C178',nm:'Luffy'},
    {id:'C179',nm:'Luffy'},
    {id:'C180',nm:'Zoro'},
    {id:'C181',nm:'Zoro'},
    {id:'C182',nm:'Nami'},
    {id:'C183',nm:'Nami'},
    {id:'C184',nm:'Nami'},
    {id:'C185',nm:'Usopp'},
    {id:'C186',nm:'Usopp'},
    {id:'C187',nm:'Sanji'},
    {id:'C188',nm:'Sanji'},
    {id:'C189',nm:'Kaya'},
    {id:'C190',nm:'Gaimon'},
    {id:'C191',nm:'Zeff'},
    {id:'C192',nm:'Patty'},
    {id:'C193',nm:'Carne'},
    {id:'C194',nm:'Chef\'s Knife'},
    {id:'C195',nm:'Sabagashira 1'},
    {id:'C196',nm:'Yosaku'},
    {id:'C197',nm:'Johnny'},
    {id:'C198',nm:'Nojiko'},
    {id:'C199',nm:'Bell-mère'},
    {id:'C200',nm:'Bell-mère and Children'},
    {id:'C201',nm:'Cocoyasi Townspeople'},
    {id:'C202',nm:'Fullbody'},
    {id:'C203',nm:'Smoker',r:'g'},
    {id:'C204',nm:'Tashigi'},
    {id:'C205',nm:'Kuro'},
    {id:'C206',nm:'Jango'},
    {id:'C207',nm:'Krieg'},
    {id:'C208',nm:'Krieg'},
    {id:'C209',nm:'Gin'},
    {id:'C210',nm:'Gin'},
    {id:'C211',nm:'Pearl'},
    {id:'C212',nm:'Arlong',r:'g'},
    {id:'C213',nm:'Arlong\'s Weapon'},
    {id:'C214',nm:'Hatchan'},
    {id:'C215',nm:'Kuroobi'},
    {id:'C216',nm:'Chew'},
    {id:'C217',nm:'Momoo'},
    {id:'C218',nm:'Black Cat Pirates'},
    {id:'C219',nm:'Krieg Assault Force'},
    {id:'C220',nm:'Arlong Crew'},
    {id:'S40',nm:'Luffy Pirates',r:'h'},
    {id:'S41',nm:'Luffy',r:'g'},
    {id:'S42',nm:'Zoro',r:'h'},
    {id:'S43',nm:'Nami'},
    {id:'S44',nm:'Usopp'},
    {id:'S45',nm:'Sanji'},
    {id:'S46',nm:'Zeff'},
    {id:'S47',nm:'Mihawk'},
    {id:'S48',nm:'Kuro'},
    {id:'S49',nm:'Krieg'},
    {id:'S50',nm:'Arlong',r:'h'},
    {id:'FP13',nm:'Decisive Battle on the Slope'},
    {id:'FP14',nm:'Krieg\'s Giant Galley'},
    {id:'FP15',nm:'Baratie Customer Service'},
    {id:'FP16',nm:'Arlong Park'},
    {id:'FP17',nm:'Cocoyasi Village'},
    {id:'FP18',nm:'Voyage of the Going Merry'},
  ]},
  {key:'FIFTH',title:'5th Stage',sub:'Aug 2000',cards:[
    {id:'C221',nm:'Luffy',r:'h'},
    {id:'C222',nm:'Luffy'},
    {id:'C223',nm:'Luffy',r:'h'},
    {id:'C224',nm:'Fishman Nami',r:'h'},
    {id:'C225',nm:'Zoro',r:'h'},
    {id:'C226',nm:'Zoro',r:'h'},
    {id:'C227',nm:'Yubashiri'},
    {id:'C228',nm:'Sandai Kitetsu'},
    {id:'C229',nm:'Nami'},
    {id:'C230',nm:'Nami'},
    {id:'C231',nm:'Nami'},
    {id:'C232',nm:'Usopp'},
    {id:'C233',nm:'Usopp'},
    {id:'C234',nm:'Sanji'},
    {id:'C235',nm:'Sanji'},
    {id:'C236',nm:'Sanji'},
    {id:'C237',nm:'Yosaku'},
    {id:'C238',nm:'Johnny'},
    {id:'C239',nm:'Genzo'},
    {id:'C240',nm:'Nojiko'},
    {id:'C241',nm:'Bell-mère'},
    {id:'C242',nm:'Ipponmatsu'},
    {id:'C243',nm:'Nezumi'},
    {id:'C244',nm:'Tashigi'},
    {id:'C245',nm:'Shikure'},
    {id:'C246',nm:'Arlong'},
    {id:'C247',nm:'Arlong'},
    {id:'C248',nm:'Hatchan'},
    {id:'C249',nm:'Kuroobi'},
    {id:'C250',nm:'Chew'},
    {id:'C251',nm:'Momoo'},
    {id:'C252',nm:'Buggy'},
    {id:'C253',nm:'Arlong\'s Crew'},
    {id:'C254',nm:'Buggy\'s Crew'},
    {id:'S51',nm:'Luffy',r:'h'},
    {id:'S52',nm:'Zoro',r:'h'},
    {id:'S53',nm:'Shanks',r:'h'},
    {id:'S54',nm:'Smoker',r:'h'},
    {id:'S55',nm:'Arlong',r:'h'},
    {id:'S56',nm:'Alvida',r:'h'},
    {id:'FP19',nm:'Nami\'s Survey Room'},
    {id:'FP20',nm:'Loguetown'},
  ]},
  {key:'SIXTH',title:'Sixth Stage',sub:'Nov 2000',cards:[
    {id:'C255',nm:'Luffy',r:'h'},
    {id:'C256',nm:'Luffy'},
    {id:'C257',nm:'Luffy'},
    {id:'C258',nm:'Zoro'},
    {id:'C259',nm:'Zoro'},
    {id:'C260',nm:'Zoro'},
    {id:'C261',nm:'Nami'},
    {id:'C262',nm:'Nami'},
    {id:'C263',nm:'Usopp'},
    {id:'C264',nm:'Usopp'},
    {id:'C265',nm:'Sanji'},
    {id:'C266',nm:'Sanji'},
    {id:'C267',nm:'Shanks'},
    {id:'C268',nm:'Nojiko'},
    {id:'C269',nm:'Bell-mère'},
    {id:'C270',nm:'Apis'},
    {id:'C271',nm:'Ryuuji'},
    {id:'C272',nm:'Dragon'},
    {id:'C273',nm:'Pudding Pudding'},
    {id:'C274',nm:'Nezumi'},
    {id:'C275',nm:'Brannew'},
    {id:'C276',nm:'Smoker',r:'h'},
    {id:'C277',nm:'Nelson Royale'},
    {id:'C278',nm:'Marine HQ Forces'},
    {id:'C279',nm:'Arlong'},
    {id:'C280',nm:'Hatchan'},
    {id:'C281',nm:'Kuroobi'},
    {id:'C282',nm:'Chew'},
    {id:'C283',nm:'Alvida'},
    {id:'C284',nm:'Buggy'},
    {id:'C285',nm:'Cabaji'},
    {id:'C286',nm:'Richie Bike'},
    {id:'C287',nm:'Eric'},
    {id:'S57',nm:'Luffy Pirates',r:'h'},
    {id:'S58',nm:'Luffy'},
    {id:'S59',nm:'Zoro',r:'h'},
    {id:'S60',nm:'Sanji',r:'h'},
    {id:'S61',nm:'Dragon',r:'h'},
    {id:'S62',nm:'Buggy'},
    {id:'S63',nm:'Arlong'},
    {id:'FP21',nm:'Pirate King\'s Execution Platform'},
    {id:'FP22',nm:'Lost Island'},
  ]},
  {key:'GB3',title:'Grand Box 3',sub:'Dec 2000',cards:[
    {id:'C288',nm:'Luffy',r:'g'},
    {id:'C289',nm:'Luffy'},
    {id:'C290',nm:'Luffy'},
    {id:'C291',nm:'Zoro',r:'g'},
    {id:'C292',nm:'Zoro'},
    {id:'C293',nm:'Zoro'},
    {id:'C294',nm:'Nami'},
    {id:'C295',nm:'Nami'},
    {id:'C296',nm:'Nami'},
    {id:'C297',nm:'Usopp'},
    {id:'C298',nm:'Usopp'},
    {id:'C299',nm:'Usopp'},
    {id:'C300',nm:'Sanji',r:'g'},
    {id:'C301',nm:'Sanji'},
    {id:'C302',nm:'Sanji'},
    {id:'C303',nm:'Shanks'},
    {id:'C304',nm:'Beckmann'},
    {id:'C305',nm:'Lucky Roux'},
    {id:'C306',nm:'Makino'},
    {id:'C307',nm:'Yosaku & Johnny'},
    {id:'C308',nm:'Bell-mère and Children'},
    {id:'C309',nm:'Apis'},
    {id:'C310',nm:'Ryuuji'},
    {id:'C311',nm:'Bokuden'},
    {id:'C312',nm:'Dragon'},
    {id:'C313',nm:'Koby'},
    {id:'C314',nm:'Helmeppo'},
    {id:'C315',nm:'Smoker',r:'h'},
    {id:'C316',nm:'Tashigi'},
    {id:'C317',nm:'Nelson Royale'},
    {id:'C318',nm:'Loguetown Garrison'},
    {id:'C319',nm:'Royale Marine Corps.'},
    {id:'C320',nm:'Arlong'},
    {id:'C321',nm:'Hatchan'},
    {id:'C322',nm:'Kuroobi'},
    {id:'C323',nm:'Chew'},
    {id:'C324',nm:'Alvida'},
    {id:'C325',nm:'Buggy'},
    {id:'C326',nm:'Cabaji & Mohji'},
    {id:'C327',nm:'Richie'},
    {id:'C328',nm:'Eric'},
    {id:'C329',nm:'Bat'},
    {id:'C330',nm:'Captain Joke'},
    {id:'S64',nm:'Luffy Pirates',r:'h'},
    {id:'S65',nm:'Luffy'},
    {id:'S66',nm:'Zoro'},
    {id:'S67',nm:'Apis',r:'h'},
    {id:'S68',nm:'Smoker'},
    {id:'S69',nm:'Tashigi'},
    {id:'S70',nm:'Arlong'},
    {id:'S71',nm:'Alvida'},
    {id:'S72',nm:'Buggy'},
    {id:'S73',nm:'Eric'},
    {id:'S74',nm:'Captain Roger'},
    {id:'FP23',nm:'Gosa Village'},
    {id:'FP24',nm:'Freedom Banquet'},
    {id:'FP25',nm:'Town Full of Monsters'},
    {id:'FP26',nm:'Warship Island'},
    {id:'FP27',nm:'Arlong\'s Pirate Ship'},
    {id:'FP28',nm:'Merry Meal'},
  ]},
  {key:'SEVENTH',title:'Seventh Stage',sub:'Feb 2001',cards:[
    {id:'C331',nm:'Luffy'},
    {id:'C332',nm:'Luffy'},
    {id:'C333',nm:'Zoro'},
    {id:'C334',nm:'Zoro'},
    {id:'C335',nm:'Zoro'},
    {id:'C336',nm:'Nami'},
    {id:'C337',nm:'Nami'},
    {id:'C338',nm:'Log Pose'},
    {id:'C339',nm:'Usopp'},
    {id:'C340',nm:'Usopp'},
    {id:'C341',nm:'Sanji',r:'h'},
    {id:'C342',nm:'Sanji'},
    {id:'C343',nm:'Sanji'},
    {id:'C344',nm:'Carmen'},
    {id:'C345',nm:'Apis'},
    {id:'C346',nm:'Borodo'},
    {id:'C347',nm:'Akisu'},
    {id:'C348',nm:'Crocus'},
    {id:'C349',nm:'Laboon',r:'h'},
    {id:'C350',nm:'Smoker'},
    {id:'C351',nm:'Tashigi'},
    {id:'C352',nm:'Den Den Mushi'},
    {id:'C353',nm:'Daddy'},
    {id:'C354',nm:'Buggy & Alvida'},
    {id:'C355',nm:'Eric'},
    {id:'C356',nm:'Captain Joke'},
    {id:'C357',nm:'Bear King',r:'h'},
    {id:'C358',nm:'Pin Joker'},
    {id:'C359',nm:'Skunk One'},
    {id:'C360',nm:'Honey Queen'},
    {id:'C361',nm:'Boo Jack'},
    {id:'C362',nm:'Mr. 9',r:'h'},
    {id:'C363',nm:'Miss Wednesday',r:'h'},
    {id:'C364',nm:'Luffy Pirates'},
    {id:'S75',nm:'Luffy Pirates',r:'h'},
    {id:'S76',nm:'Luffy',r:'h'},
    {id:'S77',nm:'Usopp'},
    {id:'S78',nm:'Ryuuji'},
    {id:'S79',nm:'Laboon'},
    {id:'S80',nm:'Bear King'},
    {id:'S81',nm:'Unluckies'},
    {id:'FP29',nm:'Clockwork Island'},
    {id:'FP30',nm:'Reverse Mountain'},
  ]},
  {key:'GB4',title:'Grand Box 4',sub:'Apr 2001',cards:[
    {id:'C365',nm:'Luffy',r:'h'},
    {id:'C366',nm:'Luffy'},
    {id:'C367',nm:'Zoro'},
    {id:'C368',nm:'Zoro'},
    {id:'C369',nm:'Nami'},
    {id:'C370',nm:'Nami'},
    {id:'C371',nm:'Usopp'},
    {id:'C372',nm:'Usopp'},
    {id:'C373',nm:'Sanji'},
    {id:'C374',nm:'Sanji'},
    {id:'C375',nm:'Shanks'},
    {id:'C376',nm:'Apis'},
    {id:'C377',nm:'Ryuuji'},
    {id:'C378',nm:'Crocus & Laboon'},
    {id:'C379',nm:'Crocus'},
    {id:'C380',nm:'Laboon'},
    {id:'C381',nm:'Vivi'},
    {id:'C382',nm:'Karoo'},
    {id:'C383',nm:'Guardians of the City'},
    {id:'C384',nm:'Pin Joker'},
    {id:'C385',nm:'Skunk One'},
    {id:'C386',nm:'Honey Queen'},
    {id:'C387',nm:'Boo Jack'},
    {id:'C388',nm:'King Cannon'},
    {id:'C389',nm:'Mr. 5',r:'g'},
    {id:'C390',nm:'Mr. 8'},
    {id:'C391',nm:'Mr. 9'},
    {id:'C392',nm:'Mr. 9'},
    {id:'C393',nm:'Miss Valentine',r:'g'},
    {id:'C394',nm:'Miss Monday'},
    {id:'C395',nm:'Miss Wednesday'},
    {id:'C396',nm:'Metal Bat'},
    {id:'C397',nm:'Peacock Slicer'},
    {id:'S82',nm:'Luffy Pirates',r:'h'},
    {id:'S83',nm:'Bear King Gang'},
    {id:'S84',nm:'Luffy & Zoro',r:'g'},
    {id:'S85',nm:'Apis & Bokuden'},
    {id:'S86',nm:'Eric & Nelson'},
    {id:'S87',nm:'Agents'},
    {id:'S88',nm:'Luffy'},
    {id:'S89',nm:'Zoro',r:'h'},
    {id:'S90',nm:'Borodo'},
    {id:'S91',nm:'Akisu'},
    {id:'S92',nm:'Clockwork Island Residents'},
    {id:'S93',nm:'Bear King'},
    {id:'H01',nm:'Martial Arts'},
    {id:'H02',nm:'Assistance'},
    {id:'H03',nm:'Obliteration Order'},
    {id:'H04',nm:'Maneuverability'},
    {id:'H05',nm:'Pacifistic Defense'},
    {id:'H06',nm:'Fighting Spirit'},
    {id:'H07',nm:'Three Sword Style'},
    {id:'H08',nm:'Stampede'},
    {id:'H09',nm:'Forceful Seizure'},
    {id:'FP31',nm:'Logue Town Tempest'},
    {id:'FP32',nm:'Lost Island Battleground'},
    {id:'FP33',nm:'Royale Armada'},
    {id:'FP34',nm:'Sea King Nest'},
    {id:'FP35',nm:'Trump Castle'},
    {id:'FP36',nm:'Whiskey Peak'},
  ]},
  {key:'GLC1',title:'Grand Line Compilation 1',sub:'Jun 2001',cards:[
    {id:'C398',nm:'Luffy',r:'h'},
    {id:'C399',nm:'Luffy'},
    {id:'C400',nm:'Luffy'},
    {id:'C401',nm:'Zoro',r:'h'},
    {id:'C402',nm:'Zoro'},
    {id:'C403',nm:'Nami'},
    {id:'C404',nm:'Nami'},
    {id:'C405',nm:'Usopp'},
    {id:'C406',nm:'Usopp'},
    {id:'C407',nm:'Sanji'},
    {id:'C408',nm:'Sanji'},
    {id:'C409',nm:'Crocus'},
    {id:'C410',nm:'Laboon'},
    {id:'C411',nm:'Vivi'},
    {id:'C412',nm:'Karoo'},
    {id:'C413',nm:'Koby'},
    {id:'C414',nm:'Helmeppo'},
    {id:'C415',nm:'Dorry & Brogy'},
    {id:'C416',nm:'Brogy'},
    {id:'C417',nm:'Dorry'},
    {id:'C418',nm:'Mr. 3',r:'h'},
    {id:'C419',nm:'Mr. 3'},
    {id:'C420',nm:'Mr. 8'},
    {id:'C421',nm:'Mr. 8'},
    {id:'C422',nm:'Miss Goldenweek'},
    {id:'C423',nm:'Miss Goldenweek'},
    {id:'C424',nm:'Miss Valentine'},
    {id:'C425',nm:'Miss Monday'},
    {id:'C426',nm:'Mr. 9 & Miss Wednesday'},
    {id:'C427',nm:'Millions'},
    {id:'S94',nm:'Luffy Pirates'},
    {id:'S95',nm:'Agents'},
    {id:'S96',nm:'Luffy & Zoro'},
    {id:'S97',nm:'Zoro & Sanji',r:'h'},
    {id:'S98',nm:'Nami'},
    {id:'S99',nm:'Mr. 9'},
    {id:'S100',nm:'Miss All Sunday',r:'h'},
    {id:'H10',nm:'The Long Road Ahead',r:'h'},
    {id:'H11',nm:'Warrior Nation',r:'h'},
    {id:'H12',nm:'Foresight'},
    {id:'H13',nm:'Outright Lie'},
    {id:'H14',nm:'Extraordinary People'},
    {id:'H15',nm:'Organization\'s Strength'},
  ]},
  {key:'GLC2',title:'Grand Line Compilation 2',sub:'Aug 2001',cards:[
    {id:'C428',nm:'Luffy',r:'h'},
    {id:'C429',nm:'Zoro',r:'h'},
    {id:'C430',nm:'Zoro'},
    {id:'C431',nm:'Nami'},
    {id:'C432',nm:'Nami'},
    {id:'C433',nm:'Usopp'},
    {id:'C434',nm:'Sanji'},
    {id:'C435',nm:'Chopper'},
    {id:'C436',nm:'Chopper'},
    {id:'C437',nm:'Vivi'},
    {id:'C438',nm:'Karoo'},
    {id:'C439',nm:'Brogy'},
    {id:'C440',nm:'Dorry'},
    {id:'C441',nm:'Dr. Kureha',r:'h'},
    {id:'C442',nm:'Dalton'},
    {id:'C443',nm:'Dalton'},
    {id:'C444',nm:'Negikuma Maria'},
    {id:'C445',nm:'Koby'},
    {id:'C446',nm:'Helmeppo'},
    {id:'C447',nm:'Wapol'},
    {id:'C448',nm:'Chess'},
    {id:'C449',nm:'Kuromarimo'},
    {id:'C450',nm:'Mr. 3'},
    {id:'C451',nm:'Mr. 3'},
    {id:'C452',nm:'Mr. 5'},
    {id:'C453',nm:'Miss Goldenweek'},
    {id:'C454',nm:'Miss Valentine'},
    {id:'C455',nm:'Lapahn'},
    {id:'C456',nm:'Luffy Pirates'},
    {id:'S101',nm:'Luffy Pirates',r:'h'},
    {id:'S102',nm:'Luffy'},
    {id:'S103',nm:'Sanji',r:'h'},
    {id:'S104',nm:'Chopper'},
    {id:'S105',nm:'Garp'},
    {id:'S106',nm:'Mr. 2'},
    {id:'S107',nm:'Miss All Sunday'},
    {id:'H16',nm:'Superdreadnought'},
    {id:'H17',nm:'Continuous Assault'},
    {id:'H18',nm:'Complete Recovery',r:'h'},
    {id:'H19',nm:'High Speed'},
    {id:'H20',nm:'Assault Command'},
    {id:'H21',nm:'Aggression'},
  ]},
  {key:'GB5',title:'Grand Box 5',sub:'Oct 2001',cards:[
    {id:'C457',nm:'Luffy',r:'h'},
    {id:'C458',nm:'Luffy'},
    {id:'C459',nm:'Zoro'},
    {id:'C460',nm:'Zoro'},
    {id:'C461',nm:'Nami'},
    {id:'C462',nm:'Nami'},
    {id:'C463',nm:'Usopp'},
    {id:'C464',nm:'Usopp'},
    {id:'C465',nm:'Sanji'},
    {id:'C466',nm:'Sanji'},
    {id:'C467',nm:'Chopper',r:'g'},
    {id:'C468',nm:'Rumble Ball'},
    {id:'C469',nm:'Amiudake'},
    {id:'C470',nm:'Vivi'},
    {id:'C471',nm:'Karoo'},
    {id:'C472',nm:'Dorry & Brogy'},
    {id:'C473',nm:'Brogy'},
    {id:'C474',nm:'Dorry'},
    {id:'C475',nm:'Dr. Kureha'},
    {id:'C476',nm:'Dr. Hiriluk'},
    {id:'C477',nm:'Cure-All Medicine'},
    {id:'C478',nm:'Dalton'},
    {id:'C479',nm:'Dalton'},
    {id:'C480',nm:'Wapol'},
    {id:'C481',nm:'Wapol'},
    {id:'C482',nm:'Chess'},
    {id:'C483',nm:'Kuromarimo'},
    {id:'C484',nm:'Mr. 3'},
    {id:'C485',nm:'Mr. 5'},
    {id:'C486',nm:'Miss Goldenweek'},
    {id:'C487',nm:'Island Eater'},
    {id:'C488',nm:'Bliking Pirates'},
    {id:'C489',nm:'Luffy Pirates',r:'h'},
    {id:'S108',nm:'Luffy Pirates',r:'h'},
    {id:'S109',nm:'Nami & Vivi'},
    {id:'S110',nm:'Luffy',r:'g'},
    {id:'S111',nm:'Chopper'},
    {id:'S112',nm:'Chopper'},
    {id:'S113',nm:'Chopper'},
    {id:'S114',nm:'Chopper'},
    {id:'S115',nm:'Chopper'},
    {id:'S116',nm:'Crocodile',r:'g'},
    {id:'S117',nm:'Mr. 3'},
    {id:'S118',nm:'Wapol'},
    {id:'S119',nm:'Unluckies'},
    {id:'H22',nm:'Armee de L\'Air Gomu Shot'},
    {id:'H23',nm:'Kokutei Roseo'},
    {id:'H24',nm:'Quatro Axes'},
    {id:'H25',nm:'Extraordinary Battle'},
    {id:'H26',nm:'Conspiracy'},
    {id:'H27',nm:'Misrule'},
    {id:'H28',nm:'Blood of a Warrior'},
    {id:'H29',nm:'Brain Play'},
    {id:'H30',nm:'Tool Master'},
    {id:'FP37',nm:'Mr. 3\'s Villa'},
    {id:'FP38',nm:'Cyclone'},
    {id:'FP39',nm:'Bliking Ship'},
    {id:'FP40',nm:'Behind the Scenes of the National Theft'},
    {id:'FP41',nm:'Drum Castle'},
    {id:'FP42',nm:'Hiruluk\'s Sakura'},
  ]},
  {key:'GLC3',title:'Grand Line Compilation 3',sub:'Nov 2001',cards:[
    {id:'C490',nm:'Luffy'},
    {id:'C491',nm:'Luffy'},
    {id:'C492',nm:'Zoro',r:'h'},
    {id:'C493',nm:'Nami'},
    {id:'C494',nm:'Usopp'},
    {id:'C495',nm:'Usopp'},
    {id:'C496',nm:'Sanji'},
    {id:'C497',nm:'Chopper',r:'h'},
    {id:'C498',nm:'Chopper'},
    {id:'C499',nm:'Zoro & Sanji'},
    {id:'C500',nm:'Vivi'},
    {id:'C501',nm:'Dalton'},
    {id:'C502',nm:'Dalton'},
    {id:'C503',nm:'Dr. Kureha'},
    {id:'C504',nm:'Dr. Hiriluk'},
    {id:'C505',nm:'Smoker'},
    {id:'C506',nm:'Tashigi'},
    {id:'C507',nm:'Crocodile',r:'h'},
    {id:'C508',nm:'Mr. 2'},
    {id:'C509',nm:'Wapol'},
    {id:'C510',nm:'Bliking Cannon'},
    {id:'C511',nm:'Chess'},
    {id:'C512',nm:'Kuromarimo'},
    {id:'C513',nm:'Ace',r:'h'},
    {id:'C514',nm:'Hiking Bear'},
    {id:'C515',nm:'Isshi-20'},
    {id:'C516',nm:'Luffy & Chopper'},
    {id:'C517',nm:'Luffy and Friends 1'},
    {id:'C518',nm:'Luffy and Friends 2'},
    {id:'C519',nm:'Luffy and Friends 3'},
    {id:'S120',nm:'Luffy Pirates',r:'h'},
    {id:'S121',nm:'Luffy'},
    {id:'S122',nm:'Nami'},
    {id:'S123',nm:'Sanji',r:'h'},
    {id:'S124',nm:'Mr. 2'},
    {id:'S125',nm:'Wapol'},
    {id:'S126',nm:'Cobra'},
    {id:'H31',nm:'Set Sail!'},
    {id:'H32',nm:'Single Combat'},
    {id:'H33',nm:'Skilled Leader'},
    {id:'H34',nm:'Invisible Adversary'},
    {id:'H35',nm:'Edict'},
  ]},
  {key:'GBDX',title:'Grand Box DX',sub:'Dec 2001 • Luffy Pirates Vs Baroque Works',cards:[
    {id:'C520',nm:'Luffy',r:'h'},
    {id:'C521',nm:'Zoro'},
    {id:'C522',nm:'Zoro'},
    {id:'C523',nm:'Nami'},
    {id:'C524',nm:'Usopp'},
    {id:'C525',nm:'Usopp'},
    {id:'C526',nm:'Sanji'},
    {id:'C527',nm:'Sanji'},
    {id:'C528',nm:'Chopper'},
    {id:'C529',nm:'Chopper'},
    {id:'C530',nm:'Vivi'},
    {id:'C531',nm:'Ace',r:'h'},
    {id:'C532',nm:'Luffy Pirates'},
    {id:'C533',nm:'Luffy Pirates'},
    {id:'C400',nm:'Luffy',rp:true},
    {id:'C402',nm:'Zoro',rp:true},
    {id:'C403',nm:'Nami',rp:true},
    {id:'C405',nm:'Usopp',rp:true},
    {id:'C407',nm:'Sanji',rp:true},
    {id:'C411',nm:'Vivi',rp:true},
    {id:'S127',nm:'Luffy Pirates',r:'h'},
    {id:'S128',nm:'Luffy'},
    {id:'S129',nm:'Nami'},
    {id:'S130',nm:'Sanji'},
    {id:'S131',nm:'Chopper'},
    {id:'H36',nm:'Final Battle'},
    {id:'H37',nm:'Extreme Situation'},
    {id:'H38',nm:'Last Hope'},
    {id:'FP43',nm:'Nanohana Harbour'},
    {id:'FP44',nm:'The Little Great Pirate Ship'},
    {id:'FP31',nm:'Logue Town Tempest',rp:true},
    {id:'C534',nm:'Crocodile',r:'h'},
    {id:'C535',nm:'Mr. 1',r:'h'},
    {id:'C536',nm:'Mr. 2'},
    {id:'C537',nm:'Mr. 3'},
    {id:'C538',nm:'Mr. 4'},
    {id:'C539',nm:'Mr. 5'},
    {id:'C540',nm:'Mr. 8'},
    {id:'C541',nm:'Miss All Sunday'},
    {id:'C542',nm:'Miss Double Finger'},
    {id:'C543',nm:'Miss Goldenweek'},
    {id:'C544',nm:'Miss Merry Christmas'},
    {id:'C545',nm:'Miss Wednesday'},
    {id:'C546',nm:'Banchi'},
    {id:'C419',nm:'Mr. 3',rp:true},
    {id:'C420',nm:'Mr. 8',rp:true},
    {id:'C423',nm:'Miss Goldenweek',rp:true},
    {id:'C424',nm:'Miss Valentine',rp:true},
    {id:'C425',nm:'Miss Monday',rp:true},
    {id:'C426',nm:'Mr. 9 & Miss Wednesday',rp:true},
    {id:'S132',nm:'Agents',r:'h'},
    {id:'S133',nm:'Mr. 3'},
    {id:'S134',nm:'Paula'},
    {id:'S135',nm:'Miss Goldenweek'},
    {id:'S136',nm:'Miss Monday'},
    {id:'S137',nm:'Unluckies'},
    {id:'S94',nm:'Luffy Pirates',rp:true},
    {id:'S95',nm:'Agents',rp:true},
    {id:'H39',nm:'Use of Force'},
    {id:'H40',nm:'Agitation'},
    {id:'H12',nm:'Foresight',rp:true},
    {id:'H15',nm:'Organization\'s Strength',rp:true},
    {id:'FP45',nm:'Spider\'s Cafe'},
    {id:'FP46',nm:'Million\'s Fleet'},
    {id:'FP36',nm:'Whiskey Peak',rp:true},
  ]},
];
